// <auto-generated>
// Generated from Chris Titus Tech's WinUtil, config/tweaks.json
// (https://github.com/ChrisTitusTech/winutil, MIT License, Copyright (c) 2022 CT Tech Group LLC).
// Only the tweaks WinUtil applies purely through registry values are taken, with the
// values and originals exactly as WinUtil records them. Regenerate rather than edit.
// </auto-generated>

namespace OsXos.Tools.Windows;

/// <summary>The registry tweaks osXos takes from WinUtil, value for value.</summary>
public static class WinUtilTweaks
{
    const string Source = "Chris Titus Tech's WinUtil";
    const string Caution = "WinUtil lists this among its advanced tweaks: apply it only if you know you want it.";

    public static IReadOnlyList<RegistryTweak> All { get; } = new RegistryTweak[]
    {
        new(
            Slug: "tweak-activity-history",
            Category: ToolCategory.Privacy,
            Name: "Disable Activity History",
            Summary: "Stops Windows from publishing or uploading user activities while preserving clipboard history.",
            IconKey: "IconPrivacy",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Windows\\System", "EnableActivityFeed", RegValueKind.DWord, "1", null, "EnableActivityFeed (System)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Windows\\System", "PublishUserActivities", RegValueKind.DWord, "0", null, "PublishUserActivities (System)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Windows\\System", "UploadUserActivities", RegValueKind.DWord, "0", null, "UploadUserActivities (System)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Stops Windows from publishing or uploading user activities while preserving clipboard history."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\\EnableActivityFeed = 1 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\\PublishUserActivities = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\\UploadUserActivities = 0 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Disabled",
            NotAppliedLabel = "Enabled",
            Source = Source,
        },
        new(
            Slug: "tweak-consumer-features",
            Category: ToolCategory.Privacy,
            Name: "Disable Consumer Features",
            Summary: "Stops promoted app installs and reduces app suggestions from Microsoft Store content.",
            IconKey: "IconStore",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent", "DisableWindowsConsumerFeatures", RegValueKind.DWord, "1", null, "DisableWindowsConsumerFeatures (CloudContent)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Stops promoted app installs and reduces app suggestions from Microsoft Store content."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent\\DisableWindowsConsumerFeatures = 1 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Disabled",
            NotAppliedLabel = "Enabled",
            Source = Source,
        },
        new(
            Slug: "tweak-device-companion-apps",
            Category: ToolCategory.Privacy,
            Name: "Prevent Device Companion Apps",
            Summary: "Prevents additional software from being installed when plugging in devices (e.g. Ads when plugging in a monitor). Poses potential security risk.",
            IconKey: "IconDownload",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Windows\\Device Metadata", "PreventDeviceMetadataFromNetwork", RegValueKind.DWord, "1", null, "PreventDeviceMetadataFromNetwork (Device Metadata)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Prevents additional software from being installed when plugging in devices (e.g. Ads when plugging in a monitor). Poses potential security risk."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\Device Metadata\\PreventDeviceMetadataFromNetwork = 1 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Prevented",
            NotAppliedLabel = "Allowed",
            Source = Source,
        },
        new(
            Slug: "tweak-edge-debloat",
            Category: ToolCategory.Privacy,
            Name: "Debloat Microsoft Edge",
            Summary: "Disables various telemetry options, popups, and other annoyances in Edge.",
            IconKey: "IconNetwork",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\EdgeUpdate", "CreateDesktopShortcutDefault", RegValueKind.DWord, "0", null, "CreateDesktopShortcutDefault (EdgeUpdate)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "PersonalizationReportingEnabled", RegValueKind.DWord, "0", null, "PersonalizationReportingEnabled (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge\\ExtensionInstallBlocklist", "1", RegValueKind.String, "ofefcgjbeghpigppfmkologfjadafddi", null, "1 (ExtensionInstallBlocklist)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "ShowRecommendationsEnabled", RegValueKind.DWord, "0", null, "ShowRecommendationsEnabled (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "HideFirstRunExperience", RegValueKind.DWord, "1", null, "HideFirstRunExperience (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "UserFeedbackAllowed", RegValueKind.DWord, "0", null, "UserFeedbackAllowed (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "ConfigureDoNotTrack", RegValueKind.DWord, "1", null, "ConfigureDoNotTrack (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "AlternateErrorPagesEnabled", RegValueKind.DWord, "0", null, "AlternateErrorPagesEnabled (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "EdgeCollectionsEnabled", RegValueKind.DWord, "0", null, "EdgeCollectionsEnabled (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "EdgeShoppingAssistantEnabled", RegValueKind.DWord, "0", null, "EdgeShoppingAssistantEnabled (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "MicrosoftEdgeInsiderPromotionEnabled", RegValueKind.DWord, "0", null, "MicrosoftEdgeInsiderPromotionEnabled (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "ShowMicrosoftRewards", RegValueKind.DWord, "0", null, "ShowMicrosoftRewards (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "WebWidgetAllowed", RegValueKind.DWord, "0", null, "WebWidgetAllowed (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "DiagnosticData", RegValueKind.DWord, "0", null, "DiagnosticData (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "EdgeAssetDeliveryServiceEnabled", RegValueKind.DWord, "0", null, "EdgeAssetDeliveryServiceEnabled (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "WalletDonationEnabled", RegValueKind.DWord, "0", null, "WalletDonationEnabled (Edge)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Edge", "DefaultBrowserSettingsCampaignEnabled", RegValueKind.DWord, "0", null, "DefaultBrowserSettingsCampaignEnabled (Edge)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Disables various telemetry options, popups, and other annoyances in Edge."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\EdgeUpdate\\CreateDesktopShortcutDefault = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\PersonalizationReportingEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\ExtensionInstallBlocklist\\1 = ofefcgjbeghpigppfmkologfjadafddi (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\ShowRecommendationsEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\HideFirstRunExperience = 1 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\UserFeedbackAllowed = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\ConfigureDoNotTrack = 1 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\AlternateErrorPagesEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\EdgeCollectionsEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\EdgeShoppingAssistantEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\MicrosoftEdgeInsiderPromotionEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\ShowMicrosoftRewards = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\WebWidgetAllowed = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\DiagnosticData = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\EdgeAssetDeliveryServiceEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\WalletDonationEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\\DefaultBrowserSettingsCampaignEnabled = 0 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Debloated",
            NotAppliedLabel = "Not debloated",
            Unavailable = Availability.Edge,
            Caution = Caution,
            Source = Source,
        },
        new(
            Slug: "tweak-brave-debloat",
            Category: ToolCategory.Privacy,
            Name: "Debloat Brave Browser",
            Summary: "Disables various annoyances like Brave Rewards, Leo AI, Crypto Wallet and VPN.",
            IconKey: "IconNetwork",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "BraveRewardsDisabled", RegValueKind.DWord, "1", null, "BraveRewardsDisabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "BraveWalletDisabled", RegValueKind.DWord, "1", null, "BraveWalletDisabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "BraveVPNDisabled", RegValueKind.DWord, "1", null, "BraveVPNDisabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "BraveAIChatEnabled", RegValueKind.DWord, "0", null, "BraveAIChatEnabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "BraveStatsPingEnabled", RegValueKind.DWord, "0", null, "BraveStatsPingEnabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "BraveNewsDisabled", RegValueKind.DWord, "1", null, "BraveNewsDisabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "BraveTalkDisabled", RegValueKind.DWord, "1", null, "BraveTalkDisabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "TorDisabled", RegValueKind.DWord, "1", null, "TorDisabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "BraveP3AEnabled", RegValueKind.DWord, "0", null, "BraveP3AEnabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "UrlKeyedAnonymizedDataCollectionEnabled", RegValueKind.DWord, "0", null, "UrlKeyedAnonymizedDataCollectionEnabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "SafeBrowsingExtendedReportingEnabled", RegValueKind.DWord, "0", null, "SafeBrowsingExtendedReportingEnabled (Brave)"),
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\BraveSoftware\\Brave", "MetricsReportingEnabled", RegValueKind.DWord, "0", null, "MetricsReportingEnabled (Brave)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Disables various annoyances like Brave Rewards, Leo AI, Crypto Wallet and VPN."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\BraveRewardsDisabled = 1 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\BraveWalletDisabled = 1 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\BraveVPNDisabled = 1 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\BraveAIChatEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\BraveStatsPingEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\BraveNewsDisabled = 1 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\BraveTalkDisabled = 1 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\TorDisabled = 1 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\BraveP3AEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\UrlKeyedAnonymizedDataCollectionEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\SafeBrowsingExtendedReportingEnabled = 0 (undo: removed); HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\BraveSoftware\\Brave\\MetricsReportingEnabled = 0 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Debloated",
            NotAppliedLabel = "Not debloated",
            Unavailable = Availability.Brave,
            Caution = Caution,
            Source = Source,
        },
        new(
            Slug: "tweak-delivery-optimization",
            Category: ToolCategory.Network,
            Name: "Disable Delivery Optimization",
            Summary: "Stops Windows from using your bandwidth to upload updates to other PCs on the internet or local network.",
            IconKey: "IconNetwork",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Windows\\DeliveryOptimization", "DODownloadMode", RegValueKind.DWord, "0", null, "DODownloadMode (DeliveryOptimization)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Stops Windows from using your bandwidth to upload updates to other PCs on the internet or local network."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\DeliveryOptimization\\DODownloadMode = 0 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Disabled",
            NotAppliedLabel = "Enabled",
            Source = Source,
        },
        new(
            Slug: "tweak-prefer-ipv4",
            Category: ToolCategory.Network,
            Name: "Set IPv4 as Preferred",
            Summary: "Setting the IPv4 preference can have latency and security benefits on private networks where IPv6 is not configured.",
            IconKey: "IconNetwork",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SYSTEM\\CurrentControlSet\\Services\\Tcpip6\\Parameters", "DisabledComponents", RegValueKind.DWord, "32", "0", "DisabledComponents (Parameters)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Setting the IPv4 preference can have latency and security benefits on private networks where IPv6 is not configured."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip6\\Parameters\\DisabledComponents = 32 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Set",
            NotAppliedLabel = "Not set",
            Caution = Caution,
            NeedsRestart = true,
            Source = Source,
        },
        new(
            Slug: "tweak-rdp-unsigned-warning",
            Category: ToolCategory.Network,
            Name: "Disable RDP Unsigned File Warnings",
            Summary: "Disables warnings shown when launching unsigned RDP files introduced with the latest Windows 10 and 11 updates.",
            IconKey: "IconWarning",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\Client", "RedirectionWarningDialogVersion", RegValueKind.DWord, "1", null, "RedirectionWarningDialogVersion (Client)"),
                new(RegHive.CurrentUser, "SOFTWARE\\Microsoft\\Terminal Server Client", "RdpLaunchConsentAccepted", RegValueKind.DWord, "1", null, "RdpLaunchConsentAccepted (Terminal Server Client)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Disables warnings shown when launching unsigned RDP files introduced with the latest Windows 10 and 11 updates."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\Client\\RedirectionWarningDialogVersion = 1 (undo: removed); HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Terminal Server Client\\RdpLaunchConsentAccepted = 1 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Disabled",
            NotAppliedLabel = "Enabled",
            Caution = Caution,
            Source = Source,
        },
        new(
            Slug: "tweak-end-task-taskbar",
            Category: ToolCategory.Shell,
            Name: "Enable End Task With Right Click",
            Summary: "Enables option to end task when right-clicking a program in the taskbar.",
            IconKey: "IconClose",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\TaskbarDeveloperSettings", "TaskbarEndTask", RegValueKind.DWord, "1", null, "TaskbarEndTask (TaskbarDeveloperSettings)"),
            },
            RestartsExplorer: true,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Enables option to end task when right-clicking a program in the taskbar."),
                new("The values it sets", "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\TaskbarDeveloperSettings\\TaskbarEndTask = 1 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Enabled",
            NotAppliedLabel = "Not enabled",
            Source = Source,
        },
        new(
            Slug: "tweak-start-menu-previous",
            Category: ToolCategory.Shell,
            Name: "Enable Start Menu Previous Layout",
            Summary: "Bring back the old Start Menu layout from before the gradual rollout of the new one in 25H2. On newer versions of Windows this tweak will not work",
            IconKey: "IconViewGrid",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SYSTEM\\ControlSet001\\Control\\FeatureManagement\\Overrides\\8\\3036241548", "EnabledState", RegValueKind.DWord, "1", null, "EnabledState (3036241548)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Bring back the old Start Menu layout from before the gradual rollout of the new one in 25H2. On newer versions of Windows this tweak will not work"),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SYSTEM\\ControlSet001\\Control\\FeatureManagement\\Overrides\\8\\3036241548\\EnabledState = 1 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Enabled",
            NotAppliedLabel = "Not enabled",
            NeedsRestart = true,
            Source = Source,
        },
        new(
            Slug: "tweak-explorer-home-gallery",
            Category: ToolCategory.Shell,
            Name: "Disable File Explorer Home and Gallery",
            Summary: "Removes the Home and Gallery from Explorer and sets This PC as default.",
            IconKey: "IconFolder",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Software\\Classes\\CLSID\\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}", "System.IsPinnedToNameSpaceTree", RegValueKind.DWord, "0", null, "System.IsPinnedToNameSpaceTree ({f874310e-b6b7-47dc-bc84-b9e6b38f5903})"),
                new(RegHive.CurrentUser, "Software\\Classes\\CLSID\\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}", "System.IsPinnedToNameSpaceTree", RegValueKind.DWord, "0", null, "System.IsPinnedToNameSpaceTree ({e88865ea-0e1c-4e20-9aa6-edcd0212c87c})"),
                new(RegHive.CurrentUser, "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", "LaunchTo", RegValueKind.DWord, "1", null, "LaunchTo (Advanced)"),
            },
            RestartsExplorer: true,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Removes the Home and Gallery from Explorer and sets This PC as default."),
                new("The values it sets", "HKEY_CURRENT_USER\\Software\\Classes\\CLSID\\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}\\System.IsPinnedToNameSpaceTree = 0 (undo: removed); HKEY_CURRENT_USER\\Software\\Classes\\CLSID\\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}\\System.IsPinnedToNameSpaceTree = 0 (undo: removed); HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\LaunchTo = 1 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Disabled",
            NotAppliedLabel = "Enabled",
            Caution = Caution,
            Source = Source,
        },
        new(
            Slug: "tweak-tray-notifications",
            Category: ToolCategory.Shell,
            Name: "Disable System Tray Notifications & Calendar",
            Summary: "Disables all Notifications INCLUDING Calendar.",
            IconKey: "IconInfo",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Software\\Policies\\Microsoft\\Windows\\Explorer", "DisableNotificationCenter", RegValueKind.DWord, "1", null, "DisableNotificationCenter (Explorer)"),
                new(RegHive.CurrentUser, "Software\\Microsoft\\Windows\\CurrentVersion\\PushNotifications", "ToastEnabled", RegValueKind.DWord, "0", "1", "ToastEnabled (PushNotifications)"),
            },
            RestartsExplorer: true,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Disables all Notifications INCLUDING Calendar."),
                new("The values it sets", "HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\Explorer\\DisableNotificationCenter = 1 (undo: removed); HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\PushNotifications\\ToastEnabled = 0 (undo: 1)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Disabled",
            NotAppliedLabel = "Enabled",
            Caution = Caution,
            Source = Source,
        },
        new(
            Slug: "tweak-wpbt",
            Category: ToolCategory.System,
            Name: "Disable Windows Platform Binary Table (WPBT)",
            Summary: "If enabled, WPBT allows your computer vendor to execute programs at boot time, such as anti-theft software, software drivers, as well as force install software without user consent. Poses potential security risk.",
            IconKey: "IconSystem",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SYSTEM\\CurrentControlSet\\Control\\Session Manager", "DisableWpbtExecution", RegValueKind.DWord, "1", null, "DisableWpbtExecution (Session Manager)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "If enabled, WPBT allows your computer vendor to execute programs at boot time, such as anti-theft software, software drivers, as well as force install software without user consent. Poses potential security risk."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\DisableWpbtExecution = 1 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Disabled",
            NotAppliedLabel = "Enabled",
            NeedsRestart = true,
            Source = Source,
        },
        new(
            Slug: "tweak-time-utc",
            Category: ToolCategory.System,
            Name: "Set Time to UTC",
            Summary: "Essential for computers that are dual booting. Fixes the time sync with Linux systems.",
            IconKey: "IconSystem",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation", "RealTimeIsUniversal", RegValueKind.QWord, "1", "0", "RealTimeIsUniversal (TimeZoneInformation)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Essential for computers that are dual booting. Fixes the time sync with Linux systems."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation\\RealTimeIsUniversal = 1 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Set",
            NotAppliedLabel = "Not set",
            Caution = Caution,
            NeedsRestart = true,
            Source = Source,
        },
        new(
            Slug: "tweak-background-apps",
            Category: ToolCategory.System,
            Name: "Disable Background Apps",
            Summary: "Disables all Microsoft Store apps from running in the background, which has to be done individually since Windows 11.",
            IconKey: "IconSystem",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Software\\Microsoft\\Windows\\CurrentVersion\\BackgroundAccessApplications", "GlobalUserDisabled", RegValueKind.DWord, "1", "0", "GlobalUserDisabled (BackgroundAccessApplications)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Disables all Microsoft Store apps from running in the background, which has to be done individually since Windows 11."),
                new("The values it sets", "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\BackgroundAccessApplications\\GlobalUserDisabled = 1 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Disabled",
            NotAppliedLabel = "Enabled",
            Caution = Caution,
            Source = Source,
        },
        new(
            Slug: "tweak-storage-sense",
            Category: ToolCategory.Maintenance,
            Name: "Disable Storage Sense",
            Summary: "Storage Sense deletes temp files automatically.",
            IconKey: "IconMaintenance",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\StorageSense\\Parameters\\StoragePolicy", "01", RegValueKind.DWord, "0", "1", "01 (StoragePolicy)"),
            },
            RestartsExplorer: false,
            AppliedText: "WinUtil's values are set.",
            RevertedText: "the original values are restored.",
            Steps: new ToolStep[]
            {
                new("What it does", "Storage Sense deletes temp files automatically."),
                new("The values it sets", "HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\StorageSense\\Parameters\\StoragePolicy\\01 = 0 (undo: 1)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = false,
            AppliedLabel = "Disabled",
            NotAppliedLabel = "Enabled",
            Caution = Caution,
            Source = Source,
        },
        new(
            Slug: "tweak-detailed-bsod",
            Category: ToolCategory.System,
            Name: "BSoD Verbose Mode",
            Summary: "Gives more information when you blue screen.",
            IconKey: "IconWarning",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SYSTEM\\CurrentControlSet\\Control\\CrashControl", "DisplayParameters", RegValueKind.DWord, "1", "0", "DisplayParameters (CrashControl)"),
                new(RegHive.LocalMachine, "SYSTEM\\CurrentControlSet\\Control\\CrashControl", "DisableEmoticon", RegValueKind.DWord, "1", "0", "DisableEmoticon (CrashControl)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Gives more information when you blue screen."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\CrashControl\\DisplayParameters = 1 (undo: 0); HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\CrashControl\\DisableEmoticon = 1 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            NeedsRestart = true,
            Source = Source,
        },
        new(
            Slug: "tweak-verbose-logon",
            Category: ToolCategory.System,
            Name: "Logon Verbose Mode",
            Summary: "Show detailed messages during startup/shutdown.",
            IconKey: "IconInfo",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System", "VerboseStatus", RegValueKind.DWord, "1", "0", "VerboseStatus (System)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Show detailed messages during startup/shutdown."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\VerboseStatus = 1 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-new-outlook",
            Category: ToolCategory.System,
            Name: "Microsoft Outlook New Version",
            Summary: "This will ensure the new Outlook application is used.",
            IconKey: "IconSystem",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "SOFTWARE\\Microsoft\\Office\\16.0\\Outlook\\Preferences", "UseNewOutlook", RegValueKind.DWord, "1", "0", "UseNewOutlook (Preferences)"),
                new(RegHive.CurrentUser, "Software\\Microsoft\\Office\\16.0\\Outlook\\Options\\General", "HideNewOutlookToggle", RegValueKind.DWord, "0", "1", "HideNewOutlookToggle (General)"),
                new(RegHive.CurrentUser, "Software\\Policies\\Microsoft\\Office\\16.0\\Outlook\\Options\\General", "DoNewOutlookAutoMigration", RegValueKind.DWord, "0", "0", "DoNewOutlookAutoMigration (General)"),
                new(RegHive.CurrentUser, "Software\\Policies\\Microsoft\\Office\\16.0\\Outlook\\Preferences", "NewOutlookMigrationUserSetting", RegValueKind.DWord, "0", null, "NewOutlookMigrationUserSetting (Preferences)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "This will ensure the new Outlook application is used."),
                new("The values it sets", "HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Office\\16.0\\Outlook\\Preferences\\UseNewOutlook = 1 (undo: 0); HKEY_CURRENT_USER\\Software\\Microsoft\\Office\\16.0\\Outlook\\Options\\General\\HideNewOutlookToggle = 0 (undo: 1); HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Office\\16.0\\Outlook\\Options\\General\\DoNewOutlookAutoMigration = 0 (undo: 0); HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Office\\16.0\\Outlook\\Preferences\\NewOutlookMigrationUserSetting = 0 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-mouse-acceleration",
            Category: ToolCategory.System,
            Name: "Mouse Acceleration",
            Summary: "Makes it so Cursor movement is affected by the speed of your physical mouse movements.",
            IconKey: "IconSystem",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Control Panel\\Mouse", "MouseSpeed", RegValueKind.DWord, "1", "0", "MouseSpeed (Mouse)"),
                new(RegHive.CurrentUser, "Control Panel\\Mouse", "MouseThreshold1", RegValueKind.DWord, "6", "0", "MouseThreshold1 (Mouse)"),
                new(RegHive.CurrentUser, "Control Panel\\Mouse", "MouseThreshold2", RegValueKind.DWord, "10", "0", "MouseThreshold2 (Mouse)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Makes it so Cursor movement is affected by the speed of your physical mouse movements."),
                new("The values it sets", "HKEY_CURRENT_USER\\Control Panel\\Mouse\\MouseSpeed = 1 (undo: 0); HKEY_CURRENT_USER\\Control Panel\\Mouse\\MouseThreshold1 = 6 (undo: 0); HKEY_CURRENT_USER\\Control Panel\\Mouse\\MouseThreshold2 = 10 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-numlock-startup",
            Category: ToolCategory.System,
            Name: "Num Lock on Startup",
            Summary: "Toggle the Num Lock key state when your computer starts.",
            IconKey: "IconSystem",
            Values: new TweakValue[]
            {
                new(RegHive.Users, ".DEFAULT\\Control Panel\\Keyboard", "InitialKeyboardIndicators", RegValueKind.String, "2", "0", "InitialKeyboardIndicators (Keyboard)"),
                new(RegHive.CurrentUser, "Control Panel\\Keyboard", "InitialKeyboardIndicators", RegValueKind.String, "2", "0", "InitialKeyboardIndicators (Keyboard)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggle the Num Lock key state when your computer starts."),
                new("The values it sets", "HKEY_USERS\\.DEFAULT\\Control Panel\\Keyboard\\InitialKeyboardIndicators = 2 (undo: 0); HKEY_CURRENT_USER\\Control Panel\\Keyboard\\InitialKeyboardIndicators = 2 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-standby-network",
            Category: ToolCategory.System,
            Name: "S0 Sleep Network Connectivity",
            Summary: "Toggles network connectivity during S0 Sleep which is low power idle in modern laptops.",
            IconKey: "IconNetwork",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "SOFTWARE\\Policies\\Microsoft\\Power\\PowerSettings\\f15576e8-98b7-4186-b944-eafa664402d9", "ACSettingIndex", RegValueKind.DWord, "1", "0", "ACSettingIndex (f15576e8-98b7-4186-b944-eafa664402d9)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggles network connectivity during S0 Sleep which is low power idle in modern laptops."),
                new("The values it sets", "HKEY_CURRENT_USER\\SOFTWARE\\Policies\\Microsoft\\Power\\PowerSettings\\f15576e8-98b7-4186-b944-eafa664402d9\\ACSettingIndex = 1 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-s3-sleep",
            Category: ToolCategory.System,
            Name: "S3 Sleep",
            Summary: "Toggles between Modern Standby and S3 Sleep, which cuts off power to the CPU while continuing to refresh the memory.",
            IconKey: "IconSystem",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SYSTEM\\CurrentControlSet\\Control\\Power", "PlatformAoAcOverride", RegValueKind.DWord, "0", null, "PlatformAoAcOverride (Power)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggles between Modern Standby and S3 Sleep, which cuts off power to the CPU while continuing to refresh the memory."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Power\\PlatformAoAcOverride = 0 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            NeedsRestart = true,
            Source = Source,
        },
        new(
            Slug: "tweak-sticky-keys",
            Category: ToolCategory.System,
            Name: "Sticky Keys",
            Summary: "Toggles the Sticky Keys, which activate when clicking shift rapidly.",
            IconKey: "IconSystem",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Control Panel\\Accessibility\\StickyKeys", "Flags", RegValueKind.DWord, "506", "58", "Flags (StickyKeys)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggles the Sticky Keys, which activate when clicking shift rapidly."),
                new("The values it sets", "HKEY_CURRENT_USER\\Control Panel\\Accessibility\\StickyKeys\\Flags = 506 (undo: 58)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-game-mode",
            Category: ToolCategory.System,
            Name: "Game Mode",
            Summary: "Toggles Windows prioritizes gaming performance by allocating system resources to games.",
            IconKey: "IconPlay",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Software\\Microsoft\\GameBar", "AllowAutoGameMode", RegValueKind.DWord, "1", "0", "AllowAutoGameMode (GameBar)"),
                new(RegHive.CurrentUser, "Software\\Microsoft\\GameBar", "AutoGameModeEnabled", RegValueKind.DWord, "1", "0", "AutoGameModeEnabled (GameBar)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggles Windows prioritizes gaming performance by allocating system resources to games."),
                new("The values it sets", "HKEY_CURRENT_USER\\Software\\Microsoft\\GameBar\\AllowAutoGameMode = 1 (undo: 0); HKEY_CURRENT_USER\\Software\\Microsoft\\GameBar\\AutoGameModeEnabled = 1 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-battery-percentage",
            Category: ToolCategory.Shell,
            Name: "System Tray Battery Percentage",
            Summary: "Shows numeric battery percentage next to the battery icon in the system tray.",
            IconKey: "IconInfo",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", "IsBatteryPercentageEnabled", RegValueKind.DWord, "1", null, "IsBatteryPercentageEnabled (Advanced)"),
            },
            RestartsExplorer: true,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Shows numeric battery percentage next to the battery icon in the system tray."),
                new("The values it sets", "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\IsBatteryPercentageEnabled = 1 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-scrollbars-visible",
            Category: ToolCategory.Shell,
            Name: "Scrollbars Always Visible",
            Summary: "If enabled, scrollbars will always be visible. If disabled, Windows will automatically hide scrollbars when not in use.",
            IconKey: "IconViewList",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Control Panel\\Accessibility", "DynamicScrollbars", RegValueKind.DWord, "0", "1", "DynamicScrollbars (Accessibility)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "If enabled, scrollbars will always be visible. If disabled, Windows will automatically hide scrollbars when not in use."),
                new("The values it sets", "HKEY_CURRENT_USER\\Control Panel\\Accessibility\\DynamicScrollbars = 0 (undo: 1)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-window-snapping",
            Category: ToolCategory.Shell,
            Name: "Window Snapping",
            Summary: "Toggles the window snapping feature when dragging windows.",
            IconKey: "IconViewGrid",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Control Panel\\Desktop", "WindowArrangementActive", RegValueKind.String, "1", "0", "WindowArrangementActive (Desktop)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggles the window snapping feature when dragging windows."),
                new("The values it sets", "HKEY_CURRENT_USER\\Control Panel\\Desktop\\WindowArrangementActive = 1 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-settings-home",
            Category: ToolCategory.Shell,
            Name: "Settings Home Page",
            Summary: "Toggles the Home Page in the Windows Settings app.",
            IconKey: "IconSettings",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer", "SettingsPageVisibility", RegValueKind.String, "show:home", "hide:home", "SettingsPageVisibility (Explorer)"),
            },
            RestartsExplorer: true,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggles the Home Page in the Windows Settings app."),
                new("The values it sets", "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\SettingsPageVisibility = show:home (undo: hide:home)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-logon-blur",
            Category: ToolCategory.Shell,
            Name: "Logon Screen Acrylic Blur",
            Summary: "Toggles the acrylic blur effect on login screen background.",
            IconKey: "IconImage",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Windows\\System", "DisableAcrylicBackgroundOnLogon", RegValueKind.DWord, "0", "1", "DisableAcrylicBackgroundOnLogon (System)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggles the acrylic blur effect on login screen background."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\\DisableAcrylicBackgroundOnLogon = 0 (undo: 1)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-lock-screen",
            Category: ToolCategory.Shell,
            Name: "Disable Lock Screen",
            Summary: "Skips the lock screen entirely and goes directly to the sign-in screen on boot and wake.",
            IconKey: "IconPrivacy",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SOFTWARE\\Policies\\Microsoft\\Windows\\Personalization", "NoLockScreen", RegValueKind.DWord, "1", null, "NoLockScreen (Personalization)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Skips the lock screen entirely and goes directly to the sign-in screen on boot and wake."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\Personalization\\NoLockScreen = 1 (undo: removed)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-taskbar-search",
            Category: ToolCategory.Shell,
            Name: "Taskbar Search Icon",
            Summary: "Toggles the Search Button on the Taskbar.",
            IconKey: "IconSearch",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Software\\Microsoft\\Windows\\CurrentVersion\\Search", "SearchboxTaskbarMode", RegValueKind.DWord, "1", "0", "SearchboxTaskbarMode (Search)"),
            },
            RestartsExplorer: true,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggles the Search Button on the Taskbar."),
                new("The values it sets", "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Search\\SearchboxTaskbarMode = 1 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-taskbar-task-view",
            Category: ToolCategory.Shell,
            Name: "Taskbar Task View Icon",
            Summary: "Toggles the Task View Button in the Taskbar.",
            IconKey: "IconViewGrid",
            Values: new TweakValue[]
            {
                new(RegHive.CurrentUser, "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", "ShowTaskViewButton", RegValueKind.DWord, "1", "0", "ShowTaskViewButton (Advanced)"),
            },
            RestartsExplorer: true,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggles the Task View Button in the Taskbar."),
                new("The values it sets", "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\ShowTaskViewButton = 1 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            Source = Source,
        },
        new(
            Slug: "tweak-long-paths",
            Category: ToolCategory.Developer,
            Name: "Enable Long Paths",
            Summary: "Toggles support for file paths longer than 260 characters in Explorer.",
            IconKey: "IconDeveloper",
            Values: new TweakValue[]
            {
                new(RegHive.LocalMachine, "SYSTEM\\CurrentControlSet\\Control\\FileSystem", "LongPathsEnabled", RegValueKind.DWord, "1", "0", "LongPathsEnabled (FileSystem)"),
            },
            RestartsExplorer: false,
            AppliedText: "the preference is on.",
            RevertedText: "the preference is off.",
            Steps: new ToolStep[]
            {
                new("What it does", "Toggles support for file paths longer than 260 characters in Explorer."),
                new("The values it sets", "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\FileSystem\\LongPathsEnabled = 1 (undo: 0)."),
                new("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."),
                new("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
            })
        {
            IsPreference = true,
            NeedsRestart = true,
            Source = Source,
        },
    };
}
