"""Generate Tools/Windows/WinUtilTweaks.cs from WinUtil's config/tweaks.json.

Usage:
    curl -L -o tweaks.json https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/config/tweaks.json
    python scripts/gen-winutil-tweaks.py tweaks.json Tools/Windows/WinUtilTweaks.cs

Add a WinUtil key to TAKE to bring another tweak in. The script refuses any entry
that needs a script, a service change or an app removal: those are not registry
tweaks, and osXos ports them by hand if at all.

Only registry-only entries are taken: ones WinUtil applies purely by setting values
and undoes by restoring the originals it records. Script-based ones are left out.
"""
import json, sys, re
sys.stdout.reconfigure(encoding='utf-8')
t = json.loads(open(sys.argv[1], encoding='utf-8-sig').read(), strict=False)

# key -> (slug, osXos category, icon)
TAKE = {
    'WPFTweaksActivity': ('activity-history', 'Privacy', 'IconPrivacy'),
    'WPFTweaksConsumerFeatures': ('consumer-features', 'Privacy', 'IconStore'),
    'WPFTweaksPreventDeviceMetadataFromNetwork': ('device-companion-apps', 'Privacy', 'IconDownload'),
    'WPFTweaksEdgeDebloat': ('edge-debloat', 'Privacy', 'IconNetwork'),
    'WPFTweaksBraveDebloat': ('brave-debloat', 'Privacy', 'IconNetwork'),
    'WPFTweaksDeliveryOptimization': ('delivery-optimization', 'Network', 'IconNetwork'),
    'WPFTweaksIPv46': ('prefer-ipv4', 'Network', 'IconNetwork'),
    'WPFTweaksDisableWarningForUnsignedRdp': ('rdp-unsigned-warning', 'Network', 'IconWarning'),
    'WPFTweaksEndTaskOnTaskbar': ('end-task-taskbar', 'Shell', 'IconClose'),
    'WPFTweaksRevertStartMenu': ('start-menu-previous', 'Shell', 'IconViewGrid'),
    'WPFTweaksRemoveHomeAndGallery': ('explorer-home-gallery', 'Shell', 'IconFolder'),
    'WPFTweaksDisableNotifications': ('tray-notifications', 'Shell', 'IconInfo'),
    'WPFTweaksWPBT': ('wpbt', 'System', 'IconSystem'),
    'WPFTweaksUTC': ('time-utc', 'System', 'IconSystem'),
    'WPFTweaksDisableBGapps': ('background-apps', 'System', 'IconSystem'),
    'WPFTweaksStorage': ('storage-sense', 'Maintenance', 'IconMaintenance'),
    'WPFToggleDetailedBSoD': ('detailed-bsod', 'System', 'IconWarning'),
    'WPFToggleVerboseLogon': ('verbose-logon', 'System', 'IconInfo'),
    'WPFToggleNewOutlook': ('new-outlook', 'System', 'IconSystem'),
    'WPFToggleMouseAcceleration': ('mouse-acceleration', 'System', 'IconSystem'),
    'WPFToggleNumLock': ('numlock-startup', 'System', 'IconSystem'),
    'WPFToggleStandbyFix': ('standby-network', 'System', 'IconNetwork'),
    'WPFToggleS3Sleep': ('s3-sleep', 'System', 'IconSystem'),
    'WPFToggleStickyKeys': ('sticky-keys', 'System', 'IconSystem'),
    'WPFToggleGameMode': ('game-mode', 'System', 'IconPlay'),
    'WPFToggleBatteryPercentage': ('battery-percentage', 'Shell', 'IconInfo'),
    'WPFToggleScrollbars': ('scrollbars-visible', 'Shell', 'IconViewList'),
    'WPFToggleWindowSnapping': ('window-snapping', 'Shell', 'IconViewGrid'),
    'WPFToggleHideSettingsHome': ('settings-home', 'Shell', 'IconSettings'),
    'WPFToggleLoginBlur': ('logon-blur', 'Shell', 'IconImage'),
    'WPFToggleDisableLockscreen': ('lock-screen', 'Shell', 'IconPrivacy'),
    'WPFToggleTaskbarSearch': ('taskbar-search', 'Shell', 'IconSearch'),
    'WPFToggleTaskView': ('taskbar-task-view', 'Shell', 'IconViewGrid'),
    'WPFToggleLongPaths': ('long-paths', 'Developer', 'IconDeveloper'),
}

# The state pill's words, by the verb the tweak's name starts with.
LABELS = {
    'Disable': ('Disabled', 'Enabled'),
    'Enable': ('Enabled', 'Not enabled'),
    'Debloat': ('Debloated', 'Not debloated'),
    'Prevent': ('Prevented', 'Allowed'),
    'Set': ('Set', 'Not set'),
}

# Tweaks for something that may not be installed: the Availability check to use.
AVAILABILITY = {
    'WPFTweaksBraveDebloat': 'Availability.Brave',
    'WPFTweaksEdgeDebloat': 'Availability.Edge',
}

HIVE = {'HKCU': 'RegHive.CurrentUser', 'HKLM': 'RegHive.LocalMachine', 'HKU': 'RegHive.Users'}
KIND = {'DWord': 'RegValueKind.DWord', 'QWord': 'RegValueKind.QWord', 'String': 'RegValueKind.String'}
HIVE_LONG = {'HKCU': 'HKEY_CURRENT_USER', 'HKLM': 'HKEY_LOCAL_MACHINE', 'HKU': 'HKEY_USERS'}

def cs(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

def name_for(v):
    c = v['Content'].strip().replace('ConsumerFeatures', 'Consumer Features')
    m = re.match(r'^(.*?) - (Disable|Enable|Debloat|Remove|Create|Run)$', c)
    if m:
        return f"{m.group(2)} {m.group(1)}"
    m = re.match(r'^(.*?) - (Set .*)$', c)
    if m:
        return m.group(2)
    return c

def clean_desc(d):
    d = d.replace('!!THIS TWEAK WILL NOT WORK!!', 'this tweak will not work')
    return re.sub(r'\s+', ' ', d).strip()

out = []
out.append('''// <auto-generated>
// Generated from Chris Titus Tech's WinUtil, config/tweaks.json
// (https://github.com/ChrisTitusTech/winutil, MIT License, Copyright (c) 2022 CT Tech Group LLC).
// Only the tweaks WinUtil applies purely through registry values are taken, with the
// values and originals exactly as WinUtil records them. Regenerate rather than edit.
// </auto-generated>

namespace OsXos.Tools.Windows;

/// <summary>The registry tweaks osXos takes from WinUtil, value for value.</summary>
public static class WinUtilTweaks
{
    const string Source = "Chris Titus Tech's WinUtil";
    const string Caution = "WinUtil lists this among its advanced tweaks: apply it only if you know you want it.";

    public static IReadOnlyList<RegistryTweak> All { get; } = new RegistryTweak[]
    {''')

count = 0
for key, (slug, cat, icon) in TAKE.items():
    v = t[key]
    kinds = [x for x in ('service', 'InvokeScript', 'UndoScript', 'appx', 'ScheduledTask') if v.get(x)]
    assert not kinds, (key, kinds)
    regs = v['registry']
    pref = v.get('Type') == 'Toggle'
    name = name_for(v)
    desc = clean_desc(v.get('Description', ''))
    values = []
    lines_for_steps = []
    machine = False
    explorer = False
    reboot = False
    for r in regs:
        hive, path = r['Path'].split(':\\', 1)
        if hive == 'HKU' and path.lower().startswith('.default'):
            path = '.DEFAULT' + path[len('.default'):]
        if hive != 'HKCU':
            machine = True
        pl = path.lower()
        if 'explorer' in pl or 'classes\\clsid' in pl or 'currentversion\\search' in pl:
            explorer = True
        if hive == 'HKLM' and pl.startswith('system\\'):
            reboot = True
        orig = r.get('OriginalValue')
        orig_cs = 'null' if orig == '<RemoveEntry>' else cs(str(orig))
        label = f"{r['Name']} ({path.split(chr(92))[-1]})"
        values.append(f"new({HIVE[hive]}, {cs(path)}, {cs(r['Name'])}, {KIND[r['Type']]}, {cs(str(r['Value']))}, {orig_cs}, {cs(label)})")
        orig_text = 'removed' if orig == '<RemoveEntry>' else str(orig)
        lines_for_steps.append(f"{HIVE_LONG[hive]}\\{path}\\{r['Name']} = {r['Value']} (undo: {orig_text})")

    caution = v.get('category', '').startswith('z__')
    rights = ("Some of these values are machine-wide, in HKEY_LOCAL_MACHINE, so Windows asks for administrator rights once — for a single reg import of exactly these values."
              if machine else "Every value is in your own account's hive: no administrator rights, and no other account on this PC is affected.")
    steps = [
        ("What it does", desc or name),
        ("The values it sets", "; ".join(lines_for_steps) + "."),
        ("How it is applied", "osXos writes these values to a .reg file and imports it with reg.exe — exactly what double-clicking a .reg file does — then reads every value back and reports anything that did not take. " + rights),
        ("Run it again to undo", "Each value goes back to the original WinUtil records for it, or is removed where WinUtil removes it — which for a policy is Windows' own default. These are WinUtil's own values, taken from its published tweak list (MIT licensed)."),
    ]
    applied = "the preference is on." if pref else "WinUtil's values are set."
    reverted = "the preference is off." if pref else "the original values are restored."

    body = []
    body.append(f'''        new(
            Slug: {cs('tweak-' + slug)},
            Category: ToolCategory.{cat},
            Name: {cs(name)},
            Summary: {cs(desc or name)},
            IconKey: {cs(icon)},
            Values: new TweakValue[]
            {{''')
    for val in values:
        body.append(f"                {val},")
    body.append('''            },''')
    body.append(f'''            RestartsExplorer: {'true' if explorer else 'false'},
            AppliedText: {cs(applied)},
            RevertedText: {cs(reverted)},
            Steps: new ToolStep[]
            {{''')
    for title, detail in steps:
        body.append(f"                new({cs(title)}, {cs(detail)}),")
    body.append('''            })''')
    body.append('''        {''')
    body.append(f'''            IsPreference = {'true' if pref else 'false'},''')
    verb = name.split(' ', 1)[0]
    if not pref and verb in LABELS:
        body.append(f"            AppliedLabel = {cs(LABELS[verb][0])},")
        body.append(f"            NotAppliedLabel = {cs(LABELS[verb][1])},")
    if key in AVAILABILITY:
        body.append(f"            Unavailable = {AVAILABILITY[key]},")
    if caution:
        body.append('''            Caution = Caution,''')
    if reboot:
        body.append('''            NeedsRestart = true,''')
    body.append('''            Source = Source,''')
    body.append('''        },''')
    out.append('\n'.join(body))
    count += 1

out.append('''    };
}
''')
open(sys.argv[2], 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print('generated', count)
